image: ruby:2.6

stages:
  - prepare
  - codecheck
  - test

environment-setup:
  stage: prepare
  script:
    - gem install bundler -v 1.17.3
    - bundle install

rubocop:
  stage: codecheck
  script:
    - rubocop

minitest:
  stage: test
  script:
    - rake