inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'lib/blizzard_api/wow.rb'

Metrics/AbcSize:
  Max: 20

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'